### ISSUE TITLE
centroFlye_paper_scripts/rare_centromeric_k-mers

### ISSUE THREAD

**Issue by duhuipeng** [seryrzu/centroFlye_paper_scripts#2]
I don't understand the error in the jupyter
Since I downloaded your script and data, connected the server with jupyter, ran to find rare_centromeric_k-mers, and reported errors,I saw your mistake because you didn't download rel2_to_GRCh38.cram
However,I don't know exactly how to ask you the problem to generate this question
Because I saw the first error ;Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/ac37ec46683600f808cdd41eac1d55cd": Protocol not supported
but I'm curious what caused this
![image](https://user-images.githubusercontent.com/58722433/90999724-ef24b880-e5f9-11ea-8134-dc18739b9cdf.png)

**Comment by seryrzu** [comment]
Running commands like this is not supported. Please show me how you are running it in the jupyter, otherwise, I don't know what the context is.

**Comment by seryrzu** [comment]
I don't understand what you refer to 
> I saw your mistake because you didn't download rel2_to_GRCh38.cram

I explicitly said: "To rerun this analysis, please uncomment the code in the following cell". The code is downloading the file.
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/7194354/90999890-b1ce1580-e57c-11ea-9009-b468461e9248.png">

**Comment by duhuipeng** [comment]
I ran with python
![image](https://user-images.githubusercontent.com/58722433/90999887-6bb79700-e5fa-11ea-8632-2b7d6e376f3b.png)
![image](https://user-images.githubusercontent.com/58722433/90999913-7e31d080-e5fa-11ea-856e-2592b4084b3a.png)
![image](https://user-images.githubusercontent.com/58722433/90999969-9e618f80-e5fa-11ea-98ae-9594328686ea.png)
![image](https://user-images.githubusercontent.com/58722433/90999989-a8838e00-e5fa-11ea-9fad-c33ac956e135.png)

**Comment by duhuipeng** [comment]
I understand your question, you commented out, so he's not downloading, so Removing the comments makes it work
 But I've downloaded the cram,  I' m still reporting the error, saying I can't open the link
![image](https://user-images.githubusercontent.com/58722433/91000262-55f6a180-e5fb-11ea-9dd6-449d0cc54499.png)

**Comment by seryrzu** [comment]
It is very difficult to understand where the problem might be. Please, run the jupyter instead of pure pythong interpreter.

**Comment by seryrzu** [comment]
This issue might be related: https://www.biostars.org/p/389132/

**Comment by duhuipeng** [comment]
It's really like this question

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/91015224-6586e200-e61d-11ea-906c-bf7fa677accf.png)
Dear author, why do I polished_sequence not agree with the article  and the difference is quite big,What is the cause of this? I don't understand
![image](https://user-images.githubusercontent.com/58722433/91015575-ee058280-e61d-11ea-8883-9f89e2388db4.png)
 for Number of units,, I just reported the wrong thing,Is it in my path can not find the output?

**Comment by seryrzu** [comment]
Most likely because you have Flye v2.7 in the PATH as I was saying earlier.

**Comment by duhuipeng** [comment]
for Number of units, also Flye caused?

**Comment by seryrzu** [comment]
Well, you are using a wrong file to supply for NCRF. It is not what is written in the jupyter

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/91016531-76d0ee00-e61f-11ea-97dd-88c0d07b6b0d.png)
Since report.ncrf only appeared in my NCRF directory, I changed it
![image](https://user-images.githubusercontent.com/58722433/91017469-df6c9a80-e620-11ea-8f73-d129afc876b1.png)
No NCRF_star/report.ncrf in my / polishing1 directory
![image](https://user-images.githubusercontent.com/58722433/91017613-12af2980-e621-11ea-9b33-61d40e910f83.png)

**Comment by seryrzu** [comment]
Please read the instructions in the README.

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/91018127-c44e5a80-e621-11ea-9156-f74956d03c15.png)
 I have seen this, I first read the README, and then began to practice, I am doing is to draw the line that step read in the README.
 Dear author 
I couldn‘t know what you mean clearly. You want to express see in the README that I can find where I was wrong?

**Comment by duhuipeng** [comment]
I know where I was wrong, I asked a stupid question

**Comment by seryrzu** [comment]
Not stupid! I am glad this is fixed!

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/91114219-f90df080-e6b9-11ea-8597-3eaf0448fdca.png)
 Dear author, I would like to ask where this data can be downloaded, I see this is the data under your path

**Comment by seryrzu** [comment]
Hi! Yeah, this is from [RepBase](https://www.girinst.org/server/RepBase)
